version: "3.4"

services:
  jikan-rest-api:
    build:
      context: ./jikan
      dockerfile: Dockerfile
    depends_on:
      - jikan-redis
    ports:
      - "8000:80"  # External:Internal
    env_file:
      - .env
    networks:
      - default
    restart: always

  jikan-redis:
    image: redis
    restart: always
